sudo: required
services:
   - docker
before_install:
  - docker build -t khurramhanif/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=True khurramhanif/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-627417904255"
    bucket_path: "docker-react"
    on:
      branch: master
    access_key_id:
      secure: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$AWS_SECRET_KEY"